# DEV ENVIRONMENT CONFIGURATIONS


COINBASE_PRO:
  URL: "https://api.exchange.coinbase.com"
  DEV:
    KEY: "[INSERT_API_KEY]"
    SECRET: "[INSERT_API_SECRET]"
    PASSPHRASE: "[INSERT_API_PASSPHRASE]"